/// Flutter icons AppIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const _kFontPkg = null;

  static const IconData accountswitcher = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accountwallet = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addcontact = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData appia = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData at = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backupseed = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bananocurrency = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bananohorizontal = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bananologo = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btc = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData changerepresentative = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData currency = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dotemtpy = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dotfilled = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_icon = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fingerprint = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData import_icon = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData importwallet = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData language = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData max = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nanocurrency = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nanohorizontal = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nanologo = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData natricon = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData natriumhorizontal = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newwallet = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paste = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData received = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData score = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seed = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sent = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData success = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swapcurrency = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timer = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transferfunds = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trashcan = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData walletpassword = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData walletpassworddisabled = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData security = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
