/// Flutter icons AppIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const IconData theme = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData bananohorizontal = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData changerepresentative = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData language = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData backupseed = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData contact = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData bananologo = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData nanologo = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData max = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData bananocurrency = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData nanocurrency = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData security = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData sent = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData dotfilled = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData dotemtpy = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData received = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData success = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData warning = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData timer = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData info = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData btc = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData close = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData forward = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData at = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData swapcurrency = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData scan = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData notifications = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData importwallet = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData newwallet = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData back = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData paste = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData trashcan = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData currency = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData addcontact = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData fingerprint = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData export_icon = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData import_icon = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData transferfunds = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData nanohorizontal = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData natriumhorizontal = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData accountswitcher = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData accountwallet = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData score = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData seed = const IconData(0xe830, fontFamily: _kFontFam);
}
