/// Flutter icons KaliumIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  KaliumIcons
///      fonts:
///       - asset: fonts/KaliumIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class KaliumIcons {
  KaliumIcons._();

  static const _kFontFam = 'KaliumIcons';

  static const IconData close = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData forward = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData at = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData backupseed = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData language = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData changerepresentative = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData transferfunds = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData contacts = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData swapcurrency = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData notifications = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData importwallet = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData newwallet = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData back = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData paste = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData trashcan = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData currency = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData fingerprint = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData sent = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData received = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData info = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData btc = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData bananocurrency = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData success = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData nanocurrency = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData export_icon = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData import_icon = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData bananologo = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData dotfilled = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData dotemtpy = const IconData(0xe820, fontFamily: _kFontFam);
}
