release_notes({
  'default' => File.read('./fastlane/metadata/en-US/release_notes.txt'),
  'en-US' => File.read('./fastlane/metadata/en-US/release_notes.txt')
});

submission_information({
  add_id_info_serves_ads: false,
  add_id_info_tracks_action: false,
  add_id_info_tracks_install: false,
  add_id_info_uses_idfa: false,
  content_rights_has_rights: true,
  content_rights_contains_third_party_content: true,
  export_compliance_platform: 'ios',
  export_compliance_compliance_required: false,
  export_compliance_encryption_updated: false,
  export_compliance_app_type: nil,
  export_compliance_uses_encryption: true,
  export_compliance_is_exempt: true,
  export_compliance_contains_third_party_cryptography: true,
  export_compliance_contains_proprietary_cryptography: false,
  export_compliance_available_on_french_store: true 
});
