# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

TEMP_KEYCHAIN_NAME_DEFAULT = "fastlane_flutter"
TEMP_KEYCHAN_PASSWORD_DEFAULT = "temppassword"
SIGH_PROVISIONING_PROFILE_NAME = "com.avengemedia.natrium AppStore"

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_keychain(
    name: name,
    password: password,
    unlock: true,
    timeout: 0
  )  
end

platform :ios do
  desc "Build & sign iOS app"
  lane :build_ios do |options|
    begin
      sh "cp -Rp ../Runner.xcodeproj ../Runner.xcodeproj.bak"
      keychain_name = ENV['TEMP_KEYCHAIN_NAME'] || TEMP_KEYCHAIN_NAME_DEFAULT
      keychain_password = ENV['TEMP_KEYCHAIN_PASSWORD'] || TEMP_KEYCHAN_PASSWORD_DEFAULT
      ensure_temp_keychain(keychain_name, keychain_password)
      api_key = app_store_connect_api_key(
        key_id: ENV['API_KEY_ID'],
        issuer_id: ENV['API_KEY_ISSUER'],
        key_filepath: ENV['API_KEY_FILEPATH'],
        duration: 1200,
        in_house: false
      )      
      match(
        app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
        type: "appstore",
        keychain_name: keychain_name,
        keychain_password: keychain_password,
        readonly: false,
        skip_provisioning_profiles: true,
        api_key: api_key
      )
      cert(
        keychain_path: "~/Library/Keychains/#{keychain_name}-db",
        keychain_password: keychain_password,
        api_key: api_key
      )
      sigh(
        app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
        readonly: false,
        cert_id: lane_context[SharedValues::CERT_CERTIFICATE_ID],
        provisioning_name: ENV['SIGH_PROVISIONING_PROFILE_NAME'],
        ignore_profiles_with_different_name: true,
        api_key: api_key
      )
      disable_automatic_code_signing(
        path: "./Runner.xcodeproj",
        team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
        profile_name: lane_context[SharedValues::SIGH_NAME],
        profile_uuid: lane_context[SharedValues::SIGH_UUID],
        code_sign_identity: "iPhone Distribution"
      )
      sh "./flutter_build.sh --clean"
      unlock_keychain(
        path: "~/Library/Keychains/#{keychain_name}-db",
        password: keychain_password
      )      
      build_ios_app(
        export_options: {
            method: "app-store",
            provisioningProfiles: { 
              "com.avengemedia.natrium" => ENV['SIGH_PROVISIONING_PROFILE_NAME'],
            }
        }
      )
    rescue SystemExit, Interrupt
      raise
    rescue Exception => e
      delete_temp_keychain(keychain_name)
      sh "cp -Rp ../Runner.xcodeproj.bak/* ../Runner.xcodeproj/ || true"
      sh "rm -rf ../Runner.xcodeproj.bak"
      raise
    ensure
      delete_temp_keychain(keychain_name)
      sh "cp -Rp ../Runner.xcodeproj.bak/* ../Runner.xcodeproj/ || true"
      sh "rm -rf ../Runner.xcodeproj.bak"
    end
  end

  desc "Upload iOS app to app store"
  lane :deploy_ios do |options|
    api_key = app_store_connect_api_key(
      key_id: ENV['API_KEY_ID'],
      issuer_id: ENV['API_KEY_ISSUER'],
      key_filepath: ENV['API_KEY_FILEPATH'],
      duration: 1200,
      in_house: false
    )
    if options[:testflight]
      upload_to_testflight(
        api_key: api_key,
        skip_submission: true,
        ipa: ENV['IPA_PATH']
      )
    else
      deliver(
        api_key: api_key,
        skip_metadata: false,
        skip_screenshots: true,
        submit_for_review: true,
        force: true,
        ipa: ENV['IPA_PATH'],
        precheck_include_in_app_purchases: false
      )
    end
  end
end
