# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
  desc "Build & Submit"
  lane :build_android do |options|
    sh "./flutter_test.sh"
    sh "./flutter_build.sh --clean"
    
    if options[:upload]
      upload_to_play_store(
        track: options[:production] ? 'production' : 'beta',
        aab: '../build/app/outputs/bundle/release/app.aab',
        skip_upload_images: true,
        skip_upload_screenshots: true,
      )
    end
  end
end
