# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Clean, build, & upload to google play"
  lane :deploy do
    sh "./flutter_test.sh"
    sh "./flutter_build.sh --clean"
    upload_to_play_store(
       track: 'production',
       aab: '../build/app/outputs/bundle/release/app.aab',
       skip_upload_images: true,
       skip_upload_screenshots: true,
    )
  end

  desc "Build & upload to google play, skip clean"
  lane :deploy_dirty do
    sh "./flutter_test.sh"
    sh "./flutter_build.sh"
    upload_to_play_store(
       track: 'alpha',
       aab: '../build/app/outputs/bundle/release/app.aab',
       skip_upload_images: true,
       skip_upload_screenshots: true,
    )
  end
end
